id: P108A4978
initial_creation_type: input
source_metadata:
  title: Termas
  language: pt
  description: 'A collection of spiritual treasures or terma (gter ma), which were
    reportedly hidden by Guru Padmasambhava and Yeshe Tsogyal, either in the earth
    and in the minds of disciples, and then revealed at the appropriate time by ‘treasure
    revealers’ or tertön (gter ston):'
  volume:
    e026237e0fcf44fb86a5052aa0626cc0:
      title: Daily Practice of Vajrakīla
      parent: Apang Tertön
    9c53aa3665834c54b0f72ea6acaa1e44:
      title: 'The New Glorious Bestower of Immortality: A Long-Life Practice and Empowerment
        that Unites the Oral, Treasure and Visionary Teachings'
      parent: Chöje Lingpa
    340ad3eaa07b49b1b9bdfea7e06ef410:
      title: The Sādhana and Empowerment for the Extremely Close Lineage of the Long-Life
        Practice that Unites the Oral, Treasure and Visionary Teachings
      parent: Chöje Lingpa
    bdac9dd0f81c4da9ac68bb1cf461d8d5:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Chokgyur Dechen Lingpa
    8cdd8e9943de466ab7679642696b6819:
      title: 'The Concise Cleansing Offering from The Guru’s Heart Practice: Dispelling
        All Obstacles on the Path'
      parent: Chokgyur Dechen Lingpa
    859f1f6591014d2f85c85b084a768110:
      title: The Lament of Rudra
      parent: Chokgyur Dechen Lingpa
    81f5e5b8543342a5bb2c3aa8b9df1e47:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Chokgyur Dechen Lingpa
    f37e3394ccbd4466a781f43d7c2b0025:
      title: The Prayer in Six Vajra Lines
      parent: Chokgyur Dechen Lingpa
    7b18f94c414b41309fe523f352af606d:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Chokgyur Dechen Lingpa
    6c7a448985eb4bd2a12da07316655f36:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Chokgyur Dechen Lingpa
    0d043f2fb03240c191623167eddd54b9:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Chokgyur Dechen Lingpa
    7c0cf672401448f5982c9c25ff79fe0b:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Chokgyur Dechen Lingpa
    ab1f01f02812407bb8d04c44f1c2d552:
      title: Concise Daily Practice of Vajrasattva
      parent: Chokgyur Dechen Lingpa
    4584297b5b18436197ee897f15bf8090:
      title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
        of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
      parent: Chokgyur Dechen Lingpa
    c5f224a4831247d6a9addf3bf6ee8d1f:
      title: A Very Brief Prayer for Clearing Obstacles from the Path (Barche Lamsel)
      parent: Do Khyentse
    89fdfee7140446da89bd4ec434357297:
      title: Heart of Vajrasattva—The Heart of Confession, the King of Purification
        Practices, from 'The Immaculate Secret Vajrasattva'
      parent: Do Khyentse
    8ea4bd9bc1684eb28fa9e704a4bb9b1d:
      title: 'The Lightning Bolt of Compassion: A Short Prayer that Spontaneously
        Fulfils All Wishes (Sampa Lhundrupma)'
      parent: Do Khyentse
    67ca8227de434bb59ece66b5c5d03a0b:
      title: The Recitation for the Gradual Path of the Preliminaries from The Exceedingly
        Secret, Enlightened Heart-Essence of the Ḍākinī
      parent: Do Khyentse
    95c28db0197149d18a905aacfe38918c:
      title: 'The Truthful Words of a Sage: An Aspiration Prayer from the Exceedingly
        Secret, Enlightened Heart-Essence of the Ḍākinī'
      parent: Do Khyentse
    fb908b72f87945efb72f918c15a38b23:
      title: The Prayer to Guru Rinpoche for Attainments
      parent: Dodrupchen Jigme Trinle Özer
    5fbfeb073a6d44518042c7288b2a3101:
      title: 'Summoning the Spirit of Abundance: A Rain of Flowers'
      parent: Dorje Dechen Lingpa
    978fdde9c97b402d9f696bf826f1d620:
      title: The Biography of the Great Orgyen that Naturally Liberates On Sight
      parent: Dudjom Lingpa
    ea50cd7417054edb935d1eed20bfe803:
      title: A Concise Recitation of the Preliminary Practice according to the New
        Treasure of Dudjom
      parent: Dudjom Rinpoche
    7e026f0103b34f14bb9ba13713ca4f1a:
      title: A Prayer to Guru Rinpoche That Spontaneously Fulfils All Wishes (from
        the Extremely Secret Assembly of Sugatas)
      parent: Garwang Chökyi Gyaltsen
    55eef521fb1f4bb5be07cb38253644ab:
      title: 'Accomplishing the Lama through the Seven-Line Prayer: A Special Teaching
        from the Lama Sangdü'
      parent: Guru Chöwang
    7259f53cfd4d4fd3a27721776a12f615:
      title: Ārya Mañjuśrī Tantra Garbha
      parent: Guru Chöwang
    53072b10b6944a34852b7b1b91995b12:
      title: 'Emptying the Hells from their Very Depths: The Sovereign Practice for
        the Confession of all Impairments and Breakages of Vows and all Negative Actions
        and Obscurations'
      parent: Guru Chöwang
    ab54afbf054e4f0981da5f63135eec37:
      title: 'Meeting the Buddha Face to Face: A Pith Instruction on Realizing the
        Fortress, Ravine, and View of the Practice of Vajrakīla'
      parent: Guru Chöwang
    05e6785a2ee9446eaaf8b91deb4faa32:
      title: The Dhāraṇīs That Encapsulate the Essence of the Kangyur, the Collected
        Words of the Buddha
      parent: Guru Chöwang
    2bc023939eda4891ae45e5187f354154:
      title: 'The Brilliant Essence: The Ritual Manual for the Secret Embodiment of
        the Guru (Lama Sangdü)'
      parent: Guru Chöwang
    e69dbaeed4934b3eb3221799413c47f4:
      title: 'Vajrakīla Prayer: A Rain of Accomplishments'
      parent: Gyarong Khandro
    b237aae5975849d58be621a3eb631eac:
      title: A Means to Pacify the Fear of Natural Disasters
      parent: Jamyang Khyentse Chökyi Lodrö
    ef2326114ddb497191001d7f3060c056:
      title: A Brief Prayer to the Precious Master Padmākara for Swiftly Fulfilling
        Wishes
      parent: Jamyang Khyentse Wangpo
    542a0415ee4a4a0996bcce2e57b38645:
      title: Activities for Uncovering Primordial Wisdom from the Chimé Pakmé Nyingtik,
        ‘The Heart Essence of the Sublime Lady of Immortality’
      parent: Jamyang Khyentse Wangpo
    b5b050ea0e744b2f8de6c706c97be338:
      title: The General Visualization for Prayers to Guru Rinpoche
      parent: Jamyang Khyentse Wangpo
    b4ed7df0df29435c9384a82a78f81bc4:
      title: The Single-Form Daily Practice from Chimé Pakmé Nyingtik (The Heart Essence
        of the Sublime Lady of Immortality)
      parent: Jamyang Khyentse Wangpo
    f4841338b78447dfa23b4c95def40116:
      title: Maṇḍala Offering from the Tradition of Jatsön Nyingpo
      parent: Jatsön Nyingpo
    218750494d7c41c89799c7e97848b8f6:
      title: The Guidebook to the Hidden Land of Pemokö
      parent: Jatsön Nyingpo
    78cfe47e96d447fe9fb1ceb2c09f4c8a:
      title: A Powerful Pith Instruction to Abstain from Tobacco, the Tenacious Demon
        Plaguing People of Degenerate Times
      parent: Jigdral Tutop Lingpa
    d8c27ca9215e4fa6b3522c9f29b92751:
      title: 'A Glimpse of the Crucial Points: The Vidyādhara''s Manual of Concealed
        Instructions'
      parent: Jigme Lingpa
    4f940979598c40b1b5a1f1642233c824:
      title: A Glorious Garland of Great Bliss, the Root Sādhana of the Queen of Great
        Bliss, Yumka Tsogyal, from the Heart Essence of the Vast Expanse
      parent: Jigme Lingpa
    a4a044ae185a4154aca3d5dae8ba5534:
      title: A Ritual of Blessing and Empowerment for the Female Practice, from the
        Heart Essence of the Vast Expanse
      parent: Jigme Lingpa
    43f2eb1dcda04313af1b1e2c90b1853b:
      title: A Sādhana of Hayagrīva’s Assembly, from the Heart-Essence of the Vast
        Expanse
      parent: Jigme Lingpa
    fa77371c0d594e1788ac13c7c4fe49f4:
      title: Awesome Ones’ Assembly (Palchen Düpa), the Heart Practice of the Awareness-Holders
      parent: Jigme Lingpa
    3075d1bdd90f42a19aae1e9db05b2cc1:
      title: Brief Prayer of the Feast Gathering
      parent: Jigme Lingpa
    d29213dbc85a4ee3bac691bf295be1f9:
      title: Secret Path to the Mountain of Glory—A Prayer of Aspiration for the Copper-Coloured
        Mountain of Glory
      parent: Jigme Lingpa
    edbbdeaba054451ea75c31d54f7291ba:
      title: 'Skull Fragments: The Root Tantra of the Vidyādharas'
      parent: Jigme Lingpa
    6fc1c53f9f934aac8eae506f8d9e3d08:
      title: 'The Continuous Shower of Blessings: A Prayer to the Lineage of the Great
        Perfection’s Heart-Essence of the Vast Expanse (Dzogpachenpo Longchen Nyingtik)'
      parent: Jigme Lingpa
    9bf57a7a4f254c50bd9085291c65150e:
      title: The History of the Female Practice of the Queen of Great Bliss
      parent: Jigme Lingpa
    fcab4215585a4747b0f7941368e1d6db:
      title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of
        the Vast Expanse
      parent: Jigme Lingpa
    423fab55d78d418e9b3562dbc3bd610c:
      title: The Root Empowerment of the Vase Conferring Majesty from the Heart-Essence
        of the Vast Expanse
      parent: Jigme Lingpa
    7980b4cac6d24e58a1b3b50bc83784e7:
      title: The Secret Practice of the Great Compassionate One, Natural Liberation
        of Suffering
      parent: Jigme Lingpa
    ba23ef1d84434648bc38a3a36e00a9cf:
      title: The Spontaneous Vajra Song of Fulfilment and Confession
      parent: Jigme Lingpa
    404d9974df98407ebb0171081bfbef4f:
      title: 'The Treasury of the Four Activities: A Fire Offering to Yumka'
      parent: Jigme Lingpa
    60df6088b1824d9cba51a8dbc23a780c:
      title: 'The Vase of Immortal Life: The Long-Life Practice of the Vidyādharas,
        from the Heart Essence of the Vast Expanse'
      parent: Jigme Lingpa
    755f9f501ff14dc985563b5088c33cb6:
      title: The Vidyādhara Assembly (Rigdzin Düpa), the Inner Practice from the Heart
        Essence of the Vast Expanse
      parent: Jigme Lingpa
    bfcd10e5424b490688d16cd647c38835:
      title: 'The Words of the Awesome Ones: A General Overview of the Three Yogas
        from the Heart-Essence of the Vast Expanse'
      parent: Jigme Lingpa
    f3466de5d0524e74ae613c26a392f095:
      title: 'Transference: Enlightenment Without Meditation (root text)'
      parent: Jigme Lingpa
    d5f223b0ced54157b01b3be97cfda1cc:
      title: Vajra Verses on the Natural State
      parent: Jigme Lingpa
    401d24c1d6944b54b71f172ac783105b:
      title: 'Highway of the Great Yoga: A Daily Practice for the Peaceful and Wrathful
        Deities of the Self-Liberated Wisdom Mind'
      parent: Karma Lingpa
    ec8eac9bb9a14596bde79304674849b9:
      title: The Benefits of the Vajra Guru Mantra and an Explanation of Its Syllables
      parent: Karma Lingpa
    d2bb430f43d744979170c532b8b9e530:
      title: The Root Verses on the Six Bardos
      parent: Karma Lingpa
    dda9ffc294e34961aade94a6f947e99e:
      title: A Sādhana of Kurukullā from the Tidro Dharma Cycle
      parent: Khenchen Jigme Phuntsok
    e8a11b60874a413489fa1f362777bab7:
      title: 'Accomplishing All Activity: A Daily Practice of the Great and Glorious
        Dorje Drolö'
      parent: Khenchen Jigme Phuntsok
    8fbd264e08f34f95977fb25d86cc590f:
      title: Mountain Smoke Offering from The Life-Force Practice of the Vidyādharas
      parent: Lhatsün Namkha Jigme
    7cc0ac375fef45b380e65092c8bbe03e:
      title: Maṇḍala Offering from Longsal Dorje Nyingpo
      parent: Longsal Nyingpo
    f5ce50d4462f417eb16861716d039ed8:
      title: 'Liberation Upon Hearing: The History of the Great Jarung Kashor Stūpa'
      parent: Ngakchang Shakya Zangpo
    35a75f720ee440f8afdf982d19dd9587:
      title: The Sovereign of Confessions for all Impairments and Breakages, Extracted
        from the Rampant Elephant Tantra
      parent: Nyala Pema Dündul
    57d42e2c37374084bb42b96a70e51c54:
      title: A Prayer Recalling the Life and Liberation of the Precious Master Padmasambhava
      parent: Nyang Ral Nyima Özer
    99974569443b41dfa92cef80fbe61484:
      title: The Abbreviated Prayer in Seven Chapters
      parent: Nyang Ral Nyima Özer
    83cf0cdf8dd2482daceba84fe60375ec:
      title: The Pointing-the-Staff Instruction
      parent: Nyang Ral Nyima Özer
    bde7863e47a2403c93117889222161a7:
      title: A Concise History of Orgyen Padma’s Enlightened Deeds
      parent: Orgyen Lingpa
    c8879283dddc4290b52373544e5c4aa9:
      title: Yeshe Tsogyal's Prayer
      parent: Pema Lingpa
    dd15c9b099e14c758f2cfac748422e89:
      title: Aspiration Prayer from Tārā Sādhana
      parent: Ratna Lingpa
    5104c018773c466b9bb1dfea1e889102:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Rigdzin Gödem
    0d626dbddaf84bea8b5672017c351a6b:
      title: 'The Wish-Fulfilling Jewel: A Daily Sādhana of the Noble Avalokiteśvara'
      parent: Rigdzin Gödem
    428e83f32356421ba555ee9e3f126580:
      title: 'Marmé Mönlam: The Light Offering Prayer'
      parent: Rigdzin Nyima Drakpa
    6ec8ee71932343b0bcd791f4cd826ce0:
      title: A Prayer Recounting the Lives and Liberation of the Exalted Ḍākinī Mandāravā
      parent: Samten Lingpa
    0e876411e2ad43c9994c8c5f38acc690:
      title: A Concise Meditation and Mantra Recitation of Sarasvatī from the Heart
        Essence of the Ḍākinī of Suchness (Chönyi Khandrö Tuktik)
      parent: Sera Khandro
    6d4158d0e8054e7cb3fa488c9ee31868:
      title: 'The Profound Bestowal of Blessings: A Sādhana of Dorje Drolö from the
        Reality Ḍākinīs'' Secret Treasury (Chönyi Khandrö Sangdzö)'
      parent: Sera Khandro
    fea702eedac9492fb3f54dd4802c984a:
      title: Dispeller of All Samaya Corruptions and Pollutions
      parent: Sherab Özer
    e168041a497e45a98ac039219df92d21:
      title: Brief Sukhāvatī Aspiration
      parent: Tertön Mingyur Dorje
    ef7b2583a0824ce69dd489a256be1c11:
      title: Dedication from Vajravārāhī Cycle of Namchö revealed by Mingyur Dorje
      parent: Tertön Mingyur Dorje
    5a2d419a34654d5689e20df6298f13eb:
      title: Prayer to Behold Amitābha in Dreams
      parent: Tertön Mingyur Dorje
    be38c089c09c480dbf5d73225e2f2a3a:
      title: 'Inventory: The Perfectly Clear Mirror from the Razor of the Innermost
        Essence'
      parent: Tertön Sogyal
    2603368739614dd398a655c81c05a290:
      title: Sādhana of Mañjughoṣa
      parent: Tertön Sogyal
    8e3ded26e7c2409cbc8fc314c595c0b7:
      title: 'The Falling Rain of Blessings: A Prayer of Inspiration'
      parent: Tertön Sogyal
    68dcba722ea2470798db190fea106572:
      title: The Guru Yoga of the Profound Path
      parent: Tertön Sogyal
    a868c5217efd4ea18d4fa7c3a40295e1:
      title: The Method to Pacify All Epidemics, Illnesses and Pandemics from the
        Sixty Solitary Forms of Yamāntaka
      parent: Tertön Sogyal
    3a4fa0f0bed941af8e0fe6895bc69afb:
      title: The Summoning of Blessings which Brings them Swift and Fast
      parent: Tertön Sogyal
    56697afabaaa4f87a003f18f046233f2:
      title: 'The Swift Path to Great Bliss: A Sādhana of Amitābha, Buddha of Limitless
        Light'
      parent: Tertön Sogyal
    6bb1a3a8cc5a4606aec900825573fc4a:
      title: The Wisdom Mind Practice of One Kīla
      parent: Tertön Sogyal
    33f18960ebfa4646ab329fa3d657593b:
      title: 'Le''u Dünma—Chapter 1: The Prayer to the Three Kāya Guru'
      parent: Tulku Zangpo Drakpa
    3bf0aafb042a422e9506f55a8c497edf:
      title: 'Le''u Dünma—Chapter 2: The Prayer Requested by King Tri Songdetsen'
      parent: Tulku Zangpo Drakpa
    3aae5310afa24c9f9eceda41f5ea5351:
      title: 'Le''u Dünma—Chapter 3: The Prayer Requested by Khandro Yeshe Tsogyal'
      parent: Tulku Zangpo Drakpa
    65bfdaf85c0e4875b81561be0d103913:
      title: 'Le''u Dünma—Chapter 4: The Prayer Requested by Namkhe Nyingpo'
      parent: Tulku Zangpo Drakpa
    9420cf1d567244078d43e8d46f6db305:
      title: 'Le''u Dünma—Chapter 5: The Prayer Requested by Nanam Dorje Dudjom'
      parent: Tulku Zangpo Drakpa
    6789634defd841b88693f493218ac52d:
      title: 'Le''u Dünma—Chapter 6: The Prayer Requested by Prince Mutri Tsenpo'
      parent: Tulku Zangpo Drakpa
    c3431232d9a44682be7b298ef7ff0015:
      title: Le'u Dünma—Chapter 7. The Prayer to Guru Rinpoche that Spontaneously
        Fulfills All Wishes (Sampa Lhundrupma)
      parent: Tulku Zangpo Drakpa
    8f38d08ee8ea4100bcddffcb7332490b:
      title: The Means for Accomplishment called the Blazing Wheel
      parent: Tulku Zangpo Drakpa
created_at: '2022-03-01T06:17:48.637579'
last_modified_at: '2022-03-01T06:17:48.637583'
